import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

export interface ComponentProps {
  nodes: GLTFNodes;
  material?: THREE.MeshPhongMaterial;
  baseColor?: THREE.ColorRepresentation;
}

export interface EnvironmentProps {}

export type GLTFResult = GLTF & {
  nodes: GLTFNodes;
  materials: {};
};

export type GLTFNodes = {
  Circle: THREE.Mesh;
  screen: THREE.Mesh;
  screen001: THREE.Mesh;
  ['main-area']: THREE.Mesh;
  leaves: THREE.Mesh;
  ['main-area001']: THREE.Mesh;
  ['main-area002']: THREE.Mesh;
  ['main-area003']: THREE.Mesh;
  ['main-area004']: THREE.Mesh;
  ['main-area005']: THREE.Mesh;
  ['main-area006']: THREE.Mesh;
  ['main-area007']: THREE.Mesh;
  ['opt-pillar']: THREE.Mesh;
  ['opt-pillar001']: THREE.Mesh;
  ['opt-pillar002']: THREE.Mesh;
  ['opt-pillar003']: THREE.Mesh;
  ['opt-pillar004']: THREE.Mesh;
  ['opt-pillar005']: THREE.Mesh;
  ['opt-pillar006']: THREE.Mesh;
  ['opt-pillar007']: THREE.Mesh;
  ['opt-pillar008']: THREE.Mesh;
  ['opt-pillar009']: THREE.Mesh;
  ['opt-pillar010']: THREE.Mesh;
  ['opt-pillar011']: THREE.Mesh;
  ['opt-pillar012']: THREE.Mesh;
  ['opt-pillar013']: THREE.Mesh;
  ['opt-pillar014']: THREE.Mesh;
  ['opt-pillar015']: THREE.Mesh;
  ['opt-pillar016']: THREE.Mesh;
  ['opt-pillar017']: THREE.Mesh;
  ['opt-pillar018']: THREE.Mesh;
  ['opt-pillar019']: THREE.Mesh;
  ['opt-pillar020']: THREE.Mesh;
  ['opt-pillar021']: THREE.Mesh;
  ['opt-pillar022']: THREE.Mesh;
  ['opt-pillar023']: THREE.Mesh;
  ['opt-pillar024']: THREE.Mesh;
  ['opt-pillar025']: THREE.Mesh;
  ['opt-pillar026']: THREE.Mesh;
  ['opt-pillar027']: THREE.Mesh;
  ['opt-pillar028']: THREE.Mesh;
  ['opt-pillar029']: THREE.Mesh;
  ['opt-pillar030']: THREE.Mesh;
  ['opt-pillar031']: THREE.Mesh;
  ['opt-pillar032']: THREE.Mesh;
  ['opt-pillar033']: THREE.Mesh;
  ['opt-pillar034']: THREE.Mesh;
  ['opt-pillar035']: THREE.Mesh;
  ['opt-pillar036']: THREE.Mesh;
  ['opt-pillar037']: THREE.Mesh;
  ['opt-pillar038']: THREE.Mesh;
  ['opt-pillar039']: THREE.Mesh;
  ['opt-pillar040']: THREE.Mesh;
  ['opt-pillar041']: THREE.Mesh;
  ['opt-pillar042']: THREE.Mesh;
  ['opt-pillar043']: THREE.Mesh;
  ['opt-pillar044']: THREE.Mesh;
  ['opt-pillar045']: THREE.Mesh;
  ['opt-pillar046']: THREE.Mesh;
  ['opt-pillar047']: THREE.Mesh;
  ['opt-pillar048']: THREE.Mesh;
  ['opt-pillar049']: THREE.Mesh;
  fist: THREE.Mesh;
  bridge002: THREE.Mesh;
  ['upper-box001']: THREE.Mesh;
  bridge001: THREE.Mesh;
  bridge003: THREE.Mesh;
  heart: THREE.Mesh;
  dove: THREE.Mesh;
  ['painting-walls']: THREE.Mesh;
  ['love-painting']: THREE.Mesh;
  ['love-painting001']: THREE.Mesh;
  ['love-painting002']: THREE.Mesh;
  ['love-painting003']: THREE.Mesh;
  ['love-painting004']: THREE.Mesh;
  ['hope-painting']: THREE.Mesh;
  ['hope-painting001']: THREE.Mesh;
  ['hope-painting002']: THREE.Mesh;
  ['hope-painting005']: THREE.Mesh;
  ['hope-painting003']: THREE.Mesh;
  ['hope-painting004']: THREE.Mesh;
  ['hope-painting006']: THREE.Mesh;
  ['hope-painting007']: THREE.Mesh;
  ['justice-painting001']: THREE.Mesh;
  ['justice-painting']: THREE.Mesh;
  ['justice-painting002']: THREE.Mesh;
  ['justice-painting003']: THREE.Mesh;
  ['justice-painting007']: THREE.Mesh;
  ['justice-painting004']: THREE.Mesh;
  ['justice-painting005']: THREE.Mesh;
  ['justice-painting006']: THREE.Mesh;
  ['painting-walls001']: THREE.Mesh;
  ['painting-walls002']: THREE.Mesh;
  ['painting-walls003']: THREE.Mesh;
  ['painting-walls004']: THREE.Mesh;
  ['painting-walls005']: THREE.Mesh;
  ['painting-walls006']: THREE.Mesh;
  ['painting-walls007']: THREE.Mesh;
  ['painting-walls008']: THREE.Mesh;
  ['painting-walls009']: THREE.Mesh;
  ['painting-walls010']: THREE.Mesh;
  ['painting-walls011']: THREE.Mesh;
  ['painting-walls012']: THREE.Mesh;
  ['painting-walls013']: THREE.Mesh;
  ['painting-walls014']: THREE.Mesh;
  ['painting-walls015']: THREE.Mesh;
  ['painting-walls016']: THREE.Mesh;
  ['painting-walls017']: THREE.Mesh;
  ['painting-walls018']: THREE.Mesh;
  ['painting-walls019']: THREE.Mesh;
  ['painting-walls020']: THREE.Mesh;
};
