export const container: string;
export const contentContainer: string;
export const buttonContainer: string;
export const iconWrapper: string;
export const metaData: string;
export const titleContainer: string;
export const audioVisualizer: string;
export const button: string;
export const iconContainer: string;
