import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { useColyseus } from '../hooks/useColyseus';
import { useEffect, useState } from 'react';
import type { Navigator } from 'webxr';

const Canvas = dynamic(() => import('../components/webgl/canvas/canvas'), {
  ssr: false,
});

const Home: NextPage = () => {
  const { client, id, room } = useColyseus();
  const [webXRIsSupported, setWebXRIsSupported] = useState<boolean>();

  useEffect(() => {
    const webXRNavigator: Navigator = navigator as any as Navigator;

    if ('xr' in webXRNavigator) {
      webXRNavigator.xr.isSessionSupported('immersive-vr').then((supported) => {
        setWebXRIsSupported(supported);
      });
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {renderPage()}
    </div>
  );

  function renderPage() {
    if (!client || !id || !room) {
      return null;
    }

    return (
      <Canvas
        isWebXrSupported={webXRIsSupported ?? false}
        client={client}
        id={id}
        room={room}
      />
    );
  }
};

export default Home;
