import type { NextPage } from 'next';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { io, Socket } from 'socket.io-client';
import { Controls } from '../components/webgl/controls/controls';
import { ClientType } from '../types/socket';
import styles from '../styles/Home.module.scss';

const Canvas = dynamic(() => import('../components/webgl/canvas/canvas'));

const Home: NextPage = () => {
  const [socketClient, setSocketClient] = useState<Socket>();
  const [clients, setClients] = useState<ClientType>({});

  useEffect(() => {
    setSocketClient(io());

    return () => {
      if (socketClient) socketClient.disconnect();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (socketClient) {
      socketClient.on('move', (clients) => {
        setClients(clients);
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [socketClient]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {renderPage()}
    </div>
  );

  function renderPage() {
    if (!socketClient) {
      return null;
    }

    return <Canvas clients={clients} socket={socketClient} />;
  }
};

export default Home;
