import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Image from 'next/image';
import { Suspense, useEffect, useState } from 'react';
import styles from '../styles/Home.module.scss';

const Canvas = dynamic(() => import('../components/landingPageCanvas/canvas'), {
  ssr: false,
});

const Home: NextPage = () => {
  const [isSsr, setIsSsr] = useState<boolean>(true);

  useEffect(() => {
    setIsSsr(false);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Corita&apos;s dream</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <p className={styles.headerText}>
          A digital product for the Stedelijk museum Amsterdam
        </p>
      </header>
      <main className={styles.main}>
        <section className={styles.contentContainer}>
          <h1 className={styles.title}>Corita&apos;s dream </h1>
          <p className={styles.description}>
            An immersive experience that puts a magnifying glass on the ideals
            of Corita Kent. This experience is inspired by the exhibition
            Everyday, Someday and Other Stories, which can be viewed in the
            Stedelijk Museum, where developments in visual art and design from
            the 1950s to the 1980s.
          </p>
          <p className={styles.description}>
            Artists and designers show that it is a time of new possibilities
            and progress, of mass culture, pop culture and consumption, but also
            of criticism of the established order.
          </p>
          <p className={styles.description}>
            Corita is one of these revolutionary artists.
          </p>
        </section>
        <section className={styles.buttonContainer}>
          <button className={styles.button}>Enter experience</button>
        </section>
      </main>
      <footer className={styles.footer}>
        <div className={styles.stedelijkLogo}>
          <Image
            alt="Stedelijk logo"
            src="/svg/stedelijk-logo.svg"
            width={60}
            height={60}
          />
        </div>
        <Image
          className={styles.image}
          alt="Ready player me"
          src="/svg/ready-player-me.svg"
          width={60}
          height={60}
        />
        <p className={styles.copyright}> By Brian Bawuah</p>
      </footer>
      {renderCanvas()}
    </div>
  );

  function renderCanvas() {
    if (isSsr) {
      return null;
    }

    return (
      <Suspense fallback={null}>
        <Canvas />
      </Suspense>
    );
  }
};

export default Home;
