import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Image from 'next/image';
import { Suspense, useEffect, useState } from 'react';
import styles from '../styles/signin/SignIn.module.scss';
import { Provider } from '@supabase/supabase-js';
import classNames from 'classnames';
import { useUser } from '@supabase/supabase-auth-helpers/react';
import { supabase } from '../utils/supabase';
import Link from 'next/link';

const Canvas = dynamic(() => import('../components/landingPageCanvas/canvas'), {
  ssr: false,
});

const SignIn: NextPage = () => {
  const [isSsr, setIsSsr] = useState<boolean>(true); // andere manier fixen
  const user = supabase.auth.user();

  useEffect(() => {
    setIsSsr(false);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Corita&apos;s dream</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Link href="/">
          <a className={styles.logoLink}>Corita&apos;s dream</a>
        </Link>
      </header>
      <main className={styles.main}>
        <section className={styles.contentContainer}>
          <p className={styles.description}>Log in to continue</p>
          <section className={styles.buttonContainer}>
            <button
              onClick={() => signInWithOAuth('google')}
              className={classNames(styles.button, styles.google)}
            >
              Google
            </button>
            <button
              onClick={() => signInWithOAuth('facebook')}
              className={classNames(styles.button, styles.facebook)}
            >
              Facebook
            </button>
            <button
              onClick={() => console.log('clicked')}
              className={classNames(styles.button, styles.github)}
            >
              Github
            </button>
          </section>
        </section>
      </main>
      <footer className={styles.footer}>
        <div className={styles.stedelijkLogo}>
          <Image
            alt="Stedelijk logo"
            src="/svg/stedelijk-logo.svg"
            width={60}
            height={60}
          />
        </div>
        <Image
          className={styles.image}
          alt="Ready player me"
          src="/svg/ready-player-me.svg"
          width={60}
          height={60}
        />
        <p className={styles.copyright}> By Brian Bawuah</p>
      </footer>
    </div>
  );

  async function signInWithOAuth(provider: Provider) {
    const { error } = await supabase.auth.signIn(
      {
        provider,
      },
      {
        redirectTo: 'http://localhost:3000/dream',
      }
    );

    if (error) {
      throw new Error(error.message);
    }
  }
};

export default SignIn;
