/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useMemo, useRef } from 'react';
import { useGLTF, useTexture } from '@react-three/drei';
import { EnvironmentProps } from './types/types';
import { HopePaintings } from './HopePaintings';
import { JusticePaintings } from './JusticePaintings';
import { LovePaintings } from './LovePaintings';
import { Water } from 'three-stdlib';
import {
  extend,
  ReactThreeFiber,
  useFrame,
  useLoader,
  useThree,
} from '@react-three/fiber';
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass';
import { VideoScreen } from './VideoScreen';
import { GeneralPaintings } from './GeneralPaintings';

extend({ Water });

declare global {
  namespace JSX {
    interface IntrinsicElements {
      water: ReactThreeFiber.Object3DNode<Water, typeof Water>;
    }
  }
}

export const Environment: React.FC<EnvironmentProps> = (props) => {
  const { nodes } = props;
  const group = useRef<THREE.Group>();
  const waterRef = useRef<THREE.Mesh>();
  const waterNormals = useLoader(
    THREE.TextureLoader,
    '/textures/waternormals.jpg'
  );
  waterNormals.wrapS = waterNormals.wrapT = THREE.RepeatWrapping;
  const geom = useMemo(() => new THREE.PlaneGeometry(10000, 10000), []);

  const config = useMemo(
    () => ({
      textureWidth: 512,
      textureHeight: 512,
      waterNormals,
      sunDirection: new THREE.Vector3(),
      sunColor: 0xffffff,
      waterColor: 0x112133,
      distortionScale: 0.3,
      fog: false,
    }),
    [waterNormals]
  );
  const metalnessMap = useTexture('/metallic-texture.jpg');
  const normalTexture = useTexture('/normal-texture.jpg');
  normalTexture.flipY = false;
  metalnessMap.flipY = false;
  normalTexture.minFilter = THREE.LinearFilter;
  metalnessMap.minFilter = THREE.LinearFilter;

  const material = new THREE.MeshPhongMaterial({
    color: 0x252525,
    normalMap: normalTexture,
    specular: 0xff5c00,
    shininess: 25,
    specularMap: metalnessMap,
    normalScale: new THREE.Vector2(0.85, 0.85),
  });

  const emissiveMaterial = new THREE.MeshPhongMaterial({
    color: 0xff8540,
    emissiveIntensity: 5,
    emissive: 0xff8540,
    normalMap: normalTexture,
    specular: 0xff5c00,
    shininess: 1,
    specularMap: metalnessMap,
    normalScale: new THREE.Vector2(5.85, 5.85),
  });

  useFrame((state, delta) => {
    if (waterRef.current) {
      (waterRef.current.material as THREE.ShaderMaterial).uniforms.time.value +=
        delta * 0.1;
    }
  });

  return (
    <group ref={group} dispose={null} position={new THREE.Vector3(0, 0.5, 0)}>
      <mesh
        geometry={nodes.screen001.geometry}
        material={nodes.screen001.material}
      />
      <mesh geometry={nodes.environment.geometry} material={material}>
        <spotLight
          distance={200}
          color="#FFE3B8"
          intensity={2.2}
          angle={1}
          penumbra={1}
          position={[0, 20, 0]}
        />
        <spotLight
          color="#FFE3B8"
          intensity={10}
          distance={50}
          angle={1}
          penumbra={1}
          position={[1, 15, -67.1038477611397]}
        />
        <spotLight
          color="#FFE3B8"
          intensity={10}
          distance={50}
          angle={1}
          penumbra={1}
          position={[-62.817927678855646, 15, -1]}
        />

        <spotLight
          color="#FFE3B8"
          intensity={10}
          distance={50}
          angle={1}
          penumbra={1}
          position={[0.22130484492688, 15, 68.00761043552393]}
        />
      </mesh>
      <mesh geometry={nodes.floor.geometry} material={material} />
      <VideoScreen nodes={nodes} material={material} />
      <HopePaintings nodes={nodes} material={material} />
      <LovePaintings nodes={nodes} material={material} />
      <JusticePaintings nodes={nodes} material={material} />
      <GeneralPaintings nodes={nodes} material={material} />
      <mesh geometry={nodes.mountains.geometry} material={material} />
      <water
        ref={waterRef}
        args={[geom, config]}
        rotation-x={-Math.PI / 2}
        position={new THREE.Vector3(0, -0.5, 0)}
      />
      <mesh geometry={nodes.lights.geometry} material={material}></mesh>
      <mesh geometry={nodes.lights001.geometry} material={material}></mesh>
      <mesh geometry={nodes.lights002.geometry} material={material}></mesh>
    </group>
  );
};

useGLTF.preload('/environment-transformed.glb');
